# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed0ff6b755584c3b2170a9f5f2e55039acbeacdba346825717bb6f5c62ed28dc9de610d19c2b54bb54f304af5e785ce1a1ecfbe624299583f5f84daaefe0da97

test:
  secret_key_base: aedd648f4edd38720746ddca7028e3f927eca5e01bfc6df96c54ab7658774de141a740c92d4808a06bcab7bbdcd1e021746d9d8ef21ca29b11acaca5872bc1e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
